vars:
  - super_resolution/config.py:DataConfig

stages:
  unpack:
    cmd: python -m super_resolution.preprocessing.unpack
    deps:
      - ${DataConfig.raw_data}
    outs:
      - ${DataConfig.unpacked_data}:
          cache: false
  preprocess:
    cmd: python -m super_resolution.preprocessing.preprocess
    deps:
      - ${DataConfig.unpacked_data}
    outs:
      - ${DataConfig.processed_data}
    params:
      - super_resolution/config.py:
          - DataConfig.target_width
          - DataConfig.target_height
